In [1]:
import pandas as pd

In [6]:
df = pd.DataFrame({
    'col1': [1,2,3,4,5],
    'col2': [34,56,76,45,23],
    'col3': "Shubham Dixit GS React Developer".split()
})

In [7]:
df['col4'] = df['col1']**2

In [8]:
df

col1  col2       col3  col4
0     1    34    Shubham     1
1     2    56      Dixit     4
2     3    76         GS     9
3     4    45      React    16
4     5    23  Developer    25

In [9]:
df['col5'] = df['col3'].str[0]
df

col1  col2       col3  col4 col5
0     1    34    Shubham     1    S
1     2    56      Dixit     4    D
2     3    76         GS     9    G
3     4    45      React    16    R
4     5    23  Developer    25    D

In [14]:
df['col6'] = return 'S' if (df['col5'] == 'S') else return 'Z'
df

SyntaxError: invalid syntax (1663969195.py, line 1)

In [15]:
def test(a):
    return a**2

In [16]:
df['col4_4'] = df['col1'].apply(test)

In [17]:
df

col1  col2       col3  col4 col5  col4_4
0     1    34    Shubham     1    S       1
1     2    56      Dixit     4    D       4
2     3    76         GS     9    G       9
3     4    45      React    16    R      16
4     5    23  Developer    25    D      25

In [20]:
def col6mapper(x):
    if (x == 'S'):
        return 'S'
    return 'Z'

In [21]:
df['col6'] = df['col5'].apply(col6mapper)

In [23]:
df

col1  col2       col3  col4 col5  col4_4 col6
0     1    34    Shubham     1    S       1    S
1     2    56      Dixit     4    D       4    Z
2     3    76         GS     9    G       9    Z
3     4    45      React    16    R      16    Z
4     5    23  Developer    25    D      25    Z

In [24]:
# Apply is basically a function that applies the computation to a particular column value

In [26]:
df['col7'] = df['col3'].apply(len)
df

col1  col2       col3  col4 col5  col4_4 col6  col7
0     1    34    Shubham     1    S       1    S     7
1     2    56      Dixit     4    D       4    Z     5
2     3    76         GS     9    G       9    Z     2
3     4    45      React    16    R      16    Z     5
4     5    23  Developer    25    D      25    Z     9

In [27]:
import math
df['col8'] = df['col2'].apply(math.log)
df

col1  col2       col3  col4 col5  col4_4 col6  col7      col8
0     1    34    Shubham     1    S       1    S     7  3.526361
1     2    56      Dixit     4    D       4    Z     5  4.025352
2     3    76         GS     9    G       9    Z     2  4.330733
3     4    45      React    16    R      16    Z     5  3.806662
4     5    23  Developer    25    D      25    Z     9  3.135494

In [28]:
import numpy as np

In [29]:
l = ["SD", 1,2,3,4]

In [30]:
type(l)

list

In [31]:
np.array(l)

array(['SD', '1', '2', '3', '4'], dtype='<U21')

In [32]:
type(np.array(l))

numpy.ndarray

In [35]:
np.array([1,2,3,4,5,3.5]) # automatically typecasts 

array([1. , 2. , 3. , 4. , 5. , 3.5])

In [41]:
a = np.array([[1,2], [3,4,]]) # This is a matrix

In [42]:
a[1][1]

4

In [49]:
np.array([1,2,3,4], ndmin = 2)

array([[1, 2, 3, 4]])

In [50]:
a

array([[1, 2],
       [3, 4]])

In [52]:
b = np.mat([1,2,3,4,5])

In [53]:
a= [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [54]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [55]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [56]:
np.fromfunction(lambda i, j : i == j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [67]:
np.fromfunction(lambda i, j, z : i*j*z, (4,3,2), dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [68]:
a = np.fromfunction(lambda i, j, z : i*j*z, (4,3,2), dtype = int)

In [69]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [70]:
a.size

24

In [71]:
a.ndim

3

In [73]:
np.random.rand(5, 4)

array([[0.97357158, 0.35289534, 0.59715411, 0.0509166 ],
       [0.15356313, 0.12995799, 0.82237062, 0.94044376],
       [0.4051964 , 0.17868913, 0.53248871, 0.2875913 ],
       [0.37443806, 0.95787167, 0.70288727, 0.33071316],
       [0.99268362, 0.9040799 , 0.29203242, 0.74713533]])

In [77]:
np.random.randint(4, 5)

4

In [78]:
np.random.randn(4, 5)

array([[ 0.37812058,  0.54329965,  0.78831839, -0.44093033, -0.54739336],
       [ 0.1240046 , -0.23005557, -1.69041364,  0.03369957, -0.0838212 ],
       [ 0.85659041,  0.49115071, -1.16256754, -1.47842997, -1.21071994],
       [-0.29696472, -0.34118259,  0.56978708,  0.64341958, -0.74413048]])

In [79]:
pd.DataFrame(np.random.randn(4, 5))

0         1         2         3         4
0  1.093817  0.384638  0.252607 -0.028401 -0.065613
1 -0.160347  0.517355  0.256329 -0.777389 -1.455428
2  2.096818  0.018206 -0.440464 -0.040129 -0.129288
3  2.011292 -1.225729 -0.043850  2.208452  0.194994

In [83]:
a.reshape(4, 6)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])